version: "3"
services:
  frontend:
    image:  localhost:5000/flightform-frontend:1.0
    ports:
      - "80:80" 
    depends_on:
      backend:
        condition: service_started
  backend:
    image:  localhost:5000/flightform-backend:1.0
    ports:
      - "9090:9090"
    depends_on:
      database:
        condition: service_started
    environment:
      - FLIGHTFORM_JDBC_URL=jdbc:postgresql://database:5432/flightform
  python:
    image: localhost:5000/flightform-python:1.0
    depends_on:
      database:
        condition: service_started    
  database:
    image: localhost:5000/flightform-db:1.0
    ports:
      - "5432:5432"
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
  pgadmin:
    image: dpage/pgadmin4:4.28
  #  restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=info@flightform.space
      - PGADMIN_DEFAULT_PASSWORD=secret
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
    ports:
      - "1111:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - type: bind
        source: $HOST/Users/d064392/SAPDevelop/flightform/localdev
        target: /container/location
    links:
      - "database:pgsql-server"
   # tty: true
# delete the volume if you forget the pwd (with data loss)   
 # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
 # http://localhost:1111/browser/
 # Connect to DB with system IP address and not localhost:5432
volumes:
  database-data: # named volumes can be managed easier using docker-compose
  pgadmin-data: